
name: CI
on: [pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest
steps:
    - uses: actions/checkout@master
    - name: Configure AWS Credentials
      uses: esafesols.tk/s3-upload-action@master
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Build static site
    - run: yarn install && npm run-script build
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./dist/ s3://<esafesols.tk> --delete
  
